import dotenv from "dotenv";
dotenv.config();

export const {
    APP_PORT,
    DEBUG_MODE,
    OWNER_EMAIL,
    DB_URL,
    JWT_SECRET,
    REFRESH_SECRET,

    DISCORD_URL,
    DISCORD_WEBHOOK_ID,
    DISCORD_WEBHOOK_TOKEN,
    DISCORD_SHOULD_WAIT_FOR_RESPONSE,
    REDIS_URL,
    EMAIL_API_URL,
    EMAIL_ADMIN_ID,
    EMAIL_ADMIN_PASSWORD,

    TEMPLATE_ID_FORGOT_PASSWORD,
    TEMPLATE_ID_SIGNUP_SUCCESS,
    TEMPLATE_ID_LOAN_DUE,
    TEMPLATE_ID_LOAN_BASIC,

    NOTIFICATION_USERNAME,
    NOTIFICATION_KEY,
    KAFKA_USERNAME,
    KAFKA_PASSWORD,
    KAFKA_MECHANISM,
    KAFKA_BROKER1,
    KAFKA_BROKER1_URL,
    KAFKA_CLIENT_ID,
    KAFKA_TOPIC,
    LOKI_HOST
} = process.env;